// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXpRlpMb1GCxYqKvH22R8-p_bwNwgplU',
    appId: '1:514035903477:web:6568abb88063d2d5a68ebc',
    messagingSenderId: '514035903477',
    projectId: 'metroferia-express-74e32',
    authDomain: 'metroferia-express-74e32.firebaseapp.com',
    storageBucket: 'metroferia-express-74e32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKNIAinuwFaCBgHaT9CxtQUaFLb8r_uTM',
    appId: '1:514035903477:android:479a4554a87e2f98a68ebc',
    messagingSenderId: '514035903477',
    projectId: 'metroferia-express-74e32',
    storageBucket: 'metroferia-express-74e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWJZasJejYA_vSz-97RVG3bHiCNqvKhd8',
    appId: '1:514035903477:ios:170422b8760f1549a68ebc',
    messagingSenderId: '514035903477',
    projectId: 'metroferia-express-74e32',
    storageBucket: 'metroferia-express-74e32.firebasestorage.app',
    iosBundleId: 'com.example.metroFeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWJZasJejYA_vSz-97RVG3bHiCNqvKhd8',
    appId: '1:514035903477:ios:170422b8760f1549a68ebc',
    messagingSenderId: '514035903477',
    projectId: 'metroferia-express-74e32',
    storageBucket: 'metroferia-express-74e32.firebasestorage.app',
    iosBundleId: 'com.example.metroFeria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXpRlpMb1GCxYqKvH22R8-p_bwNwgplU',
    appId: '1:514035903477:web:6b92ad2aad729a98a68ebc',
    messagingSenderId: '514035903477',
    projectId: 'metroferia-express-74e32',
    authDomain: 'metroferia-express-74e32.firebaseapp.com',
    storageBucket: 'metroferia-express-74e32.firebasestorage.app',
  );
}
